### ISSUE TITLE
Add support for new battle move segments

### ISSUE THREAD

**Issue by Pronyo-Chan** [pmret/papermario#1031]
I'm trying to add a new battle move and each one of them is defined as its own segment in splat.yaml.
Example of a vanilla move:

```
- name: battle_move_hammer_attack
    dir: battle/move/hammer
    type: code
    start: 0x7345A0
    vram: 0x802A1000
    follows_vram: battle_code
    subsegments:
    - [0x7345A0, c, attack]
    - [0x734650]
```

 I tried adding it under the basic hammer attack segment like so:
```
- name: battle_move_fire_attack
    dir: battle/move/fire
    type: code
    subsegments:
    - [auto, c, attack]
    - [auto]
```
and get the following error: `no segment rom overlaps symbol battle_move_hammer_IsBerserkerEquipped`. I tried also specifying the vram/ follows vram, setting start to auto, but I always end up with the same error. Ethan is pretty sure it's just not supported yet, here's a link to the discord discussion: https://discord.com/channels/279322074412089344/989948270954565772/1100558313885814854
